FROM node:22.24.0-alpine3.19

WORKDIR /app

COPY package*.json ./
RUN npm install

RUN apk update && apk upgrade --no-cache

COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]